version: "3.3"

services:
  mu:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env.local